using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FoodRescue.Api.Migrations
{
    /// <inheritdoc />
    public partial class AddOrganizationDetails : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "Organizations" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" character varying(100) NOT NULL,
                    "Type" character varying(50) NOT NULL,
                    "ContactPerson" character varying(100) NOT NULL,
                    "Email" character varying(254) NOT NULL,
                    "Phone" character varying(20) NOT NULL,
                    "Address" character varying(250) NOT NULL,
                    "Status" character varying(20) NOT NULL,
                    CONSTRAINT "PK_Organizations" PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.AddColumn<string>(
                name: "Description",
                table: "Organizations",
                type: "character varying(500)",
                maxLength: 500,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "District",
                table: "Organizations",
                type: "character varying(80)",
                maxLength: 80,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "Location",
                table: "Organizations",
                type: "character varying(250)",
                maxLength: 250,
                nullable: false,
                defaultValue: "");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Description",
                table: "Organizations");

            migrationBuilder.DropColumn(
                name: "District",
                table: "Organizations");

            migrationBuilder.DropColumn(
                name: "Location",
                table: "Organizations");
        }
    }
}
