"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { apiRequest } from "../services/api";

const fields = { donations: [["foodName", "Food name"], ["quantity", "Quantity", "number"], ["district", "District"], ["location", "Location"], ["expiryTime", "Expiry time", "datetime-local"], ["pickupTime", "Pickup time", "datetime-local"], ["status", "Status", "select", ["Available", "Claimed", "Expired"]]], foodrequests: [["foodType", "Food type"], ["requiredQuantity", "Required quantity", "number"], ["district", "District"], ["location", "Location"], ["requiredDate", "Required date", "date"], ["contactInformation", "Contact information"], ["reason", "Reason"] , ["status", "Status", "select", ["Pending", "Fulfilled", "Cancelled"]]], pickups: [["donationId", "Donation ID", "number"], ["organizationId", "Organization ID", "number"], ["pickupDate", "Pickup date", "date"], ["pickupTime", "Pickup time", "time"], ["pickupLocation", "Pickup location"], ["personResponsible", "Person responsible"], ["contactNumber", "Contact number"], ["status", "Status", "select", ["Pending", "Scheduled", "Collected", "Cancelled"]]] };

export default function CrudForm({ resource, initial = {}, id }) { const router = useRouter(); const [values, setValues] = useState(initial); const config = fields[resource]; const submit = async (e) => { e.preventDefault(); const payload = { ...values, quantity: Number(values.quantity), requiredQuantity: Number(values.requiredQuantity), donationId: Number(values.donationId), organizationId: Number(values.organizationId) }; await apiRequest(id ? `/${resource}/${id}` : `/${resource}`, { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }); router.push(`/${resource}`); }; return <form className="form-panel" onSubmit={submit}><div className="form-grid">{config.map(([name, label, type = "text", options]) => <label className="field" key={name}>{label}{type === "select" ? <select required name={name} value={values[name] || ""} onChange={(e) => setValues({ ...values, [name]: e.target.value })}><option value="">Choose a status</option>{options.map((option) => <option key={option}>{option}</option>)}</select> : <input required name={name} type={type} value={values[name] || ""} onChange={(e) => setValues({ ...values, [name]: e.target.value })} />}</label>)}</div><div className="form-actions"><Link className="button button--quiet" href={`/${resource}`}>Cancel</Link><button className="button button--primary">Save {resource}</button></div></form>; }
